<?xml version="1.0" ?>
<!DOCTYPE chords [
<!ELEMENT CHORDS (CHORD)*>
<!ELEMENT CHORD (#PCDATA)*>
<!ATTLIST CHORD id ID #REQUIRED>
]>
<CHORDS>
  <!-- major -->
  <CHORD id="C">C3 E3 G3</CHORD>
  <CHORD id="C#">C#3 F3 G#3</CHORD>
  <CHORD id="D">D3 F#3 A3</CHORD>
  <CHORD id="D#">D#3 G3 A#3</CHORD>
  <CHORD id="E">E3 G#3 B3</CHORD>
  <CHORD id="F">F3 A3 C4</CHORD>
  <CHORD id="F#">F#3 A#3 C#4</CHORD>
  <CHORD id="G">G3 B3 D4</CHORD>
  <CHORD id="G#">G#3 C4 D#4</CHORD>
  <CHORD id="A">A3 C#4 E4</CHORD>
  <CHORD id="A#">A#3 D4 F4</CHORD>
  <CHORD id="B">B3 D#4 F#4</CHORD>
  <!-- minor -->
  <CHORD id="Cm">C3 D#3 G3</CHORD>
  <CHORD id="C#m">C#3 E3 G#3</CHORD>
  <CHORD id="Dm">D3 F3 A3</CHORD>
  <CHORD id="D#m">D#3 F#3 A#3</CHORD>
  <CHORD id="Em">E3 G3 B3</CHORD>
  <CHORD id="Fm">F3 G#3 C4</CHORD>
  <CHORD id="F#m">F#3 A3 C#4</CHORD>
  <CHORD id="Gm">G3 B3 D4</CHORD>
  <CHORD id="G#m">G#3 A#3 D#4</CHORD>
  <CHORD id="Am">A3 C4 E4</CHORD>
  <CHORD id="A#m">A#3 C#4 F4</CHORD>
  <CHORD id="Bm">B3 D4 F#4</CHORD>
</CHORDS>
