<?xml version="1.0" ?>
<!DOCTYPE chords [
<!ELEMENT CHORDS (CHORD)*>
<!ELEMENT CHORD (#PCDATA)*>
<!ATTLIST CHORD id ID #REQUIRED>
]>
<CHORDS>
  <!-- major -->
  <CHORD id="C">C1 E1 G1</CHORD>
  <CHORD id="C#">C#1 F1 G#1</CHORD>
  <CHORD id="D">D1 F#1 A1</CHORD>
  <CHORD id="D#">D#1 G1 A#1</CHORD>
  <CHORD id="E">E1 G#1 B1</CHORD>
  <CHORD id="F">F1 A1 C2</CHORD>
  <CHORD id="F#">F#1 A#1 C#2</CHORD>
  <CHORD id="G">G1 B1 D2</CHORD>
  <CHORD id="G#">G#1 C2 D#2</CHORD>
  <CHORD id="A">A C#2 E2</CHORD>
  <CHORD id="A#">A#1 D2 F2</CHORD>
  <CHORD id="B">B1 D#2 F#2</CHORD>
  <!-- minor -->
  <CHORD id="Cm">C1 D#1 G1</CHORD>
  <CHORD id="C#m">C#1 E1 G#1</CHORD>
  <CHORD id="Dm">D1 F1 A1</CHORD>
  <CHORD id="D#m">D#1 F#1 A#1</CHORD>
  <CHORD id="Em">E1 G1 B1</CHORD>
  <CHORD id="Fm">F1 G#1 C2</CHORD>
  <CHORD id="F#m">F#1 A1 C#2</CHORD>
  <CHORD id="Gm">G1 B1 D2</CHORD>
  <CHORD id="G#m">G#1 A#1 D#2</CHORD>
  <CHORD id="Am">A C2 E2</CHORD>
  <CHORD id="A#m">A#1 C#2 F2</CHORD>
  <CHORD id="Bm">B1 D2 F#2</CHORD>
</CHORDS>
