<?xml version="1.0" ?>
<!DOCTYPE chords [
<!ELEMENT CHORDS (CHORD)*>
<!ELEMENT CHORD (#PCDATA)*>
<!ATTLIST CHORD id ID #REQUIRED>
]>
<CHORDS>
  <CHORD id="A">A2 E3 A3 C#4 E4</CHORD>
  <CHORD id="B">A#2 F3 A#3 D#4 F#4</CHORD>
  <CHORD id="C">C3 E3 G3 C4 E4</CHORD>
  <CHORD id="D">D3 A3 D4 F#4</CHORD>
  <CHORD id="E">E2 B2 E3 G#3 B4 E4</CHORD>
  <CHORD id="F">F3 A3 C4 F4</CHORD>
  <CHORD id="G">G2 B2 D3 G3 B4 C4</CHORD>
</CHORDS>
